name: ArpysTest
favicon: null
layout_spectrum: 0.98071
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#24232b'
    - '#404c5c'
    - '#72736e'
    - '#070512'
    - '#b599a6'
  brandStrength: 0.0738372674677521
  lightness: 0.09649643674492836
  saturation: 0.02381231472827494
  rhythmicContrast: 0.9921238147653639
purpose: []
